# Generated by Django 5.0.6 on 2024-07-03 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OverwatchProfile',
        ),
        migrations.DeleteModel(
            name='HeroStats',
        ),
        migrations.DeleteModel(
            name='MapStats',
        ),
        migrations.DeleteModel(
            name='RoleStats',
        ),
        ]
